# Generated by Django 4.1.2 on 2024-01-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='juice_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(default='Home', max_length=15)),
                ('room_number', models.CharField(blank=True, max_length=15, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('place_name', models.TextField()),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='address_images/')),
                ('is_default', models.BooleanField(default=False)),
                ('address_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.userprofile')),
            ],
        ),
    ]
