# Generated by Django 4.1.2 on 2024-01-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0002_order_iteminorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juice.address'),
        ),
    ]
