# Generated by Django 4.1.2 on 2024-01-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice', '0003_order_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
